language: c 
sudo: required

before_script:
 - chmod +x ./bin/cibuild # or do this locally and commit

before_install:
  - apt-get update
  - apt-get upgrade
  - apt-get install pandoc 

# Assume bundler is being used, therefore
# # the `install` step will run `bundle install` by default.
script: ./bin/build

# # branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
  - /blog-(.*)/  # build blog posts 

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
